# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IDPSiteMapping
                                 A QGIS plugin
 Plugin to Help with mapping of Internally Displaced Persons Structures
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-07-24
        copyright            : (C) 2024 by pascal ogola
        email                : pascaladongo@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'pascal ogola'
__date__ = '2024-07-24'
__copyright__ = '(C) 2024 by pascal ogola'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IDPSiteMapping class from file IDPSiteMapping.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .idp_sites_mapping import IDPSiteMappingPlugin
    return IDPSiteMappingPlugin()
